import { Resend } from "resend";
import { CATEGORY_ORDER } from "./config";

const resend = new Resend(process.env.RESEND_API_KEY!);

interface DigestArticle {
  title: string;
  url: string;
  source: string;
  author: string | null;
  published_at: string;
  summary: string;
  category: string;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function buildEmailHtml(articles: DigestArticle[], date: string): string {
  const grouped: Record<string, DigestArticle[]> = {};
  for (const article of articles) {
    const cat = article.category || "Other";
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(article);
  }

  // Sort within each category by published_at descending
  for (const cat of Object.keys(grouped)) {
    grouped[cat].sort(
      (a, b) =>
        new Date(b.published_at).getTime() -
        new Date(a.published_at).getTime()
    );
  }

  const sources = new Set(articles.map((a) => a.source));

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; max-width: 680px; margin: 0 auto; padding: 20px; background: #ffffff; }
    .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24px; margin: 0 0 4px 0; }
    .header .meta { font-size: 14px; color: #666; }
    .category { margin-bottom: 28px; }
    .category h2 { font-size: 16px; text-transform: uppercase; letter-spacing: 1px; color: #333; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-bottom: 14px; }
    .article { margin-bottom: 18px; padding-left: 16px; border-left: 3px solid #e0e0e0; }
    .article a { color: #1a1a1a; text-decoration: none; font-weight: bold; font-size: 16px; }
    .article a:hover { text-decoration: underline; }
    .article .source-info { font-size: 13px; color: #888; margin: 2px 0 4px 0; }
    .article .summary { font-size: 14px; color: #444; line-height: 1.5; margin: 0; }
    .footer { border-top: 1px solid #ddd; padding-top: 16px; margin-top: 32px; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Daily Antisemitism News Monitor</h1>
    <div class="meta">${date} &bull; ${articles.length} article${articles.length !== 1 ? "s" : ""} from ${sources.size} source${sources.size !== 1 ? "s" : ""}</div>
  </div>`;

  for (const category of CATEGORY_ORDER) {
    const catArticles = grouped[category];
    if (!catArticles || catArticles.length === 0) continue;

    html += `
  <div class="category">
    <h2>${category}</h2>`;

    for (const article of catArticles) {
      const authorPart = article.author ? ` &bull; ${article.author}` : "";
      html += `
    <div class="article">
      <a href="${article.url}">${escapeHtml(article.title)}</a>
      <div class="source-info">${escapeHtml(article.source)}${authorPart} &bull; ${formatDate(article.published_at)}</div>
      <p class="summary">${escapeHtml(article.summary)}</p>
    </div>`;
    }

    html += `
  </div>`;
  }

  html += `
  <div class="footer">
    <p>This digest was automatically generated by the Nexus News Monitor.</p>
    <p>Questions? Contact bryan@notionstate.com</p>
  </div>
</body>
</html>`;

  return html;
}

function buildEmptyHtml(date: string): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; max-width: 680px; margin: 0 auto; padding: 20px; }
    .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24px; margin: 0 0 4px 0; }
    .header .meta { font-size: 14px; color: #666; }
    .content { font-size: 15px; color: #444; line-height: 1.6; }
    .footer { border-top: 1px solid #ddd; padding-top: 16px; margin-top: 32px; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Daily Antisemitism News Monitor</h1>
    <div class="meta">${date}</div>
  </div>
  <div class="content">
    <p>No antisemitism-related articles were found in monitored sources for the past 24 hours.</p>
  </div>
  <div class="footer">
    <p>This digest was automatically generated by the Nexus News Monitor.</p>
    <p>Questions? Contact bryan@notionstate.com</p>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function sendDigest(articles: DigestArticle[]) {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const recipient = process.env.EMAIL_RECIPIENT || "bryan@notionstate.com";
  const hasArticles = articles.length > 0;

  const subject = hasArticles
    ? `Antisemitism News Digest - ${date}`
    : `Antisemitism News Digest - ${date} (No articles)`;

  const html = hasArticles
    ? buildEmailHtml(articles, date)
    : buildEmptyHtml(date);

  const { data, error } = await resend.emails.send({
    from: "Nexus News Monitor <onboarding@resend.dev>",
    to: [recipient],
    subject,
    html,
  });

  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }

  return {
    recipient,
    articles_included: articles.length,
    categories_included: hasArticles
      ? new Set(articles.map((a) => a.category)).size
      : 0,
    resend_message_id: data?.id || null,
  };
}
